### ISSUE TITLE
F#+ functor ... implementation

### ISSUE THREAD

**Issue by wallymathieu** [wallymathieu/fsharp-validations#2]
- [x] functor
- [x] Bifunctor
- [x] traversable
- [x] foldable 

As seen in [docs](https://gusty.github.io/FSharpPlus/abstractions.html)

[Haskell validation](https://github.com/qfpl/validation)

[goal](https://github.com/gusty/FSharpPlus/issues/51)

**Comment by gusty** [comment]
I think Alternative is not defined in the Haskell code.
``orElse`` seems to be a good candidate for ``<|>``

**Comment by wallymathieu** [comment]
I got confused by the `import Data.Functor.Alt` implementation.

**Comment by gusty** [comment]
Actually you're right. I didn't notice ``Alt``, I was looking for ``Alternative``.
From the [Haskell docs](https://hackage.haskell.org/package/semigroupoids-5.0.0.1/docs/Data-Functor-Alt.html#t:Alt) I can see that ``Alt`` is an ``Alternative`` with some more relaxed rules, so ``<!>`` it's equivalent to our ``<|>`` If I'm not overlooking it.

**Comment by gusty** [comment]
There is a lot of noise in the Haskell world regarding Alternative and MonadPlus, since there is a longstanding [reform proposal](https://wiki.haskell.org/MonadPlus_reform_proposal) and it seems people started to create different flavors of them until such reform is adopted.

**Comment by wallymathieu** [comment]
Interesting 👍
