### ISSUE TITLE
Convert examples

### ISSUE THREAD

**Issue by wallymathieu** [wallymathieu/fsharp-validations#5]
- https://github.com/qfpl/validation/tree/master/examples/src

**Comment by gusty** [comment]
I'll give it a try tonight.
But if you're blocked with something (in general in this project) let me know.

**Comment by wallymathieu** [comment]
Kew! I'm thinking of either writing some property based tests for FSharpPlus or creating a branch where  https://github.com/wallymathieu/auctions-site is more f#+y

**Comment by gusty** [comment]
Whichever you like, both seems good progress to me.
As I said at some point we should add FsCheck
I'm having a quick look to auctions-site, it seems that you will be able to delete this file https://github.com/wallymathieu/auctions-site/blob/master/Auctions/Option.fs and https://github.com/wallymathieu/auctions-site/blob/master/Auctions/Parse.fs also
 https://github.com/wallymathieu/auctions-site/blob/master/Auctions/Result.fs but will require to adapt your code to use a Monad Transformer with explicit lifting. I can help with this if you want.

**Comment by wallymathieu** [comment]
So far it seems I could get it to work: https://github.com/wallymathieu/auctions-site/pull/8/files

The messiest code right now is the following: 
```
  /// handle command and add result to repository
  let handleCommandAsync 
    (maybeC:Result<Command,_>) :Async<Result<_,_>> = 
    monad {
      match agent.UserCommand <!> maybeC with 
      | Ok asyncR-> 
          let! result = asyncR
          return result
      | Error c'->return Error c'
    }
```

I've not really grokked the explicit lifting, so I've not been able to make use of it

**Comment by wallymathieu** [comment]
I especially like how `tryParse` makes for less weird code.

**Comment by gusty** [comment]
Yes, it simplifies a lot, with the type directed resolution.
Have you noticed the generic active pattern ``Parse`` ?
That's also very handful.

**Comment by wallymathieu** [comment]
I've not noticed it, I will check it out 😄

**Comment by gusty** [comment]
Take some notes as you discover these kind of "hidden" features, so we think later how to un-hide them in the docs.
Maybe in a quick tour file?

**Comment by gusty** [comment]
I had a quick look at your code, there are maybe some small details that I can show you, but I'll let you go ahead first and try yourself.
Then when you consider it, I can review it and suggest some changes eventually.

**Comment by wallymathieu** [comment]
Since I'm a bit unfamiliar with the nomenclature for category theory, it looks more like new names for abstract algebra. The structures look the same as the structures in general algebra I studied at the university (so I get a bit extra confused).

**Comment by gusty** [comment]
Add to that the "Haskell names" (like 'Alt') ... easy to get lost. I know.
The abstractions page of the doc is the best effort to help on this.
